source 'https://rubygems.org'
gem 'httparty'
gem 'minitest'
gem 'mocha'
gem 'rack-minitest'
gem 'rack-test'
gem 'rake'
gem 'require_all'
gem 'rubocop'
gem 'shotgun'
gem 'simplecov', require: false, group: :test
gem 'sinatra'
gem 'test-spec'
gem 'test-unit'
